### ISSUE TITLE
NPC spawn underground

### ISSUE THREAD

**Issue by MEFRREEX** [Josscoder/JNPC#3]
If attribute keepLooking = true this npc always spawns 2 blocks below the desired point
![image](https://user-images.githubusercontent.com/83061703/228447151-2248c5c6-7341-4dc7-a833-cdaa2b162b56.png)
![image](https://user-images.githubusercontent.com/83061703/228447203-53967c1f-47c4-4301-ba49-1be5dc839993.png)

code
```java
@EventHandler
private void onJoin(PlayerJoinEvent event) {
        HumanAttributes humanAttributes = HumanAttributes.builder()
                .skin(event.getPlayer().getSkin())
                .handItem(new ItemEndCrystal())
                .build();

        NPC npc = NPC.create(AttributeSettings.builder()
                .networkId(EntityHuman.NETWORK_ID)
                .keepLooking(true)
                .location(event.getPlayer().getLocation())
                .controller((clickedNPC, player) -> {
                    player.sendMessage(TextFormat.colorize("Hello i'm NPC " + clickedNPC.getEntityId()));
                })
                .build(),
                humanAttributes
        );

        npc.getTagSettings()
                .addLine(new SimpleLine("&d&lFirst Header", 2))
                .addLine(new SimpleLine("&eSub header"))
                .addLine(new SimpleLine("&o&7Footer"))
                .adjust(); //ajust lines
}
```

**Comment by Josscoder** [comment]
specify the version of JNPC you are using, please

**Comment by MEFRREEX** [comment]
> specify the version of JNPC you are using, please

latest

**Comment by Josscoder** [comment]
Nukkit or powernukkit?

**Comment by MEFRREEX** [comment]
> Nukkit or powernukkit?

powernukkitx

**Comment by Josscoder** [comment]
Hi, the bug has been fixed in both branches, for powernukkitx you can use: 
`powernukkitx-a9c9016b2b-1` of jitpack
momentarily while I post a new version, please let me know if it works for you!

**Comment by MEFRREEX** [comment]
Yes, everything works great

**Comment by Josscoder** [comment]
Perfect, thank you very much, any other bug can open another issue!
