### ISSUE TITLE
Mey be go to make a new functionality

### ISSUE THREAD

**Issue by DenOrekhov567** [Josscoder/JNPC#4]
Please add method for spawning fly text particle and update this.

For example
TagFactory.create()..
and add methods for regulation their location, update text.

and method for update this text, for example. TagFactory.get(uniqueId)/* return Tag*/.addLine("lol")...

oh mannn....

**Comment by Josscoder** [comment]
hello, what do you want to do, a floating text?

**Comment by DenOrekhov567** [comment]
Yep man

**Comment by Josscoder** [comment]
just create a human entity, with the invisible skin returned by NPCUtils and add lines to it with TagSettings

**Comment by DenOrekhov567** [comment]
how to update these tags?
